### ISSUE TITLE
Remove highlight.js

### ISSUE THREAD

**Issue by angrybacon** [ddftwiki/ssg#8]
I may be missing something but all I see are wrongly emphasized keywords in the code blocks.

**Comment by Doishy** [comment]
I know at one point d8dk32 had gotten rid of the highlighting as obviously the code blocks try to be helpful in highlighting non existent code....

**Comment by emidln** [comment]
I'll remove highlight.js tonight. I think @d8dk32 moved it off-path so that it didn't load before and I "fixed" that (non-loading). I'll just kill the file and include tonight.

**Comment by emidln** [comment]
Fixed by 510a7c328ac7a461da4fce7d0d97c008d57f5145
